name: SQL Database Security Pipeline

on: 
  workflow_dispatch: 

jobs:
  apply-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Show context
      run: echo "Running for ${{ github.ref_name }}"  # bash?
    
    - name: Run script 
      env:
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        TARGET_ENV: dev
      run: |
        echo "Running for $TARGET_ENV environment"
        sqlcmd -S your_server.database.windows.net -d your_database -U your_user -P $SQL_PASSWORD -i ./Security/Login/DatabaseSecurityPipeline/CreateUser.sql
        sqlcmd -S your_server.database.windows.net -d your_database -U your_user -P $SQL_PASSWORD -i ./Security/Login/DatabaseSecurityPipeline/CreateApplicationAccess.sql
        sqlcmd -S your_server.database.windows.net -d your_database -U your_user -P $SQL_PASSWORD -i ./Security/Login/DatabaseSecurityPipeline/CreatePAAccess.sql