version: '3.8'

services:
  inventory-api:
    build:
      context: ./Inventory-API/InventoryApi
      dockerfile: Dockerfile
    container_name: inventory-api
    ports:
      - "3001:8080"
      - "3002:8081"
    depends_on:
      - inventory-db
    environment:
      - ASPNETCORE_ENVIRONMENT: Development
      - ConnectionStrings_InventoryDb: Server=inventory-db;Database=InventoryDb;User Id=sa;Password=Sampaio4240;MultipleActiveResultSets=true;TrustServerCertificate=True;

  inventory-db:
    build:
      context: ./Inventory-DB/InventoryDb
      dockerfile: Dockerfile
    container_name: inventory-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA: Y
      - MSSQL_SA_PASSWORD: YourStrongPassword123!!
      - MSSQL_PID: Developer
      - DefaultAdmin_Password: AdminPassword123!!
      - EnvironmentName: Development
      - ASPNETCORE_ENVIRONMENT: Development