/*
Deployment script for InventoryDb

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar EnvironmentName "Development"
:setvar DatabaseName "InventoryDb"
:setvar DefaultFilePrefix "InventoryDb"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar AdminPassword ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF NOT EXISTS 
    (SELECT name  
     FROM sys.database_principals
     WHERE name = 'defaultAdmin')
BEGIN
    CREATE USER defaultAdmin FOR LOGIN defaultAdmin;
    ALTER LOGIN defaultAdmin WITH PASSWORD = 'NewStrongPassword';

    PRINT 'Default User Created';
END
GO

-- Add to role only if not already in it
IF NOT EXISTS (
    SELECT dp.name
    FROM sys.database_principals dp
    JOIN sys.database_role_members drm ON dp.principal_id = drm.member_principal_id
    JOIN sys.database_principals roles ON drm.role_principal_id = roles.principal_id
    WHERE dp.name = 'defaultAdmin' AND roles.name = 'db_owner'
)
BEGIN
    ALTER ROLE db_owner ADD MEMBER defaultAdmin;
END

GO
IF OBJECT_ID('dbo.[CheckTableExist]') IS NOT NULL
BEGIN
  DROP FUNCTION dbo.[CheckTableExist]
END
GO

CREATE FUNCTION [dbo].[CheckTableExist]
(
    @fileName VARCHAR(100)
)
RETURNS TABLE
AS
RETURN (
    SELECT 
        t.name AS TableName,
        s.name AS SchemaName
    FROM sys.tables as t
    JOIN sys.schemas s ON t.schema_id = s.schema_id
    WHERE t.name LIKE '%' + @fileName + '%'
);

GO
IF NOT EXISTS (SELECT * FROM dbo.CheckTableExist('DeployOnce'))
BEGIN
	CREATE TABLE [dbo].[_deployOnce](
		[Id] INT NOT NULL,
		[FileName] [nchar](10) NULL
	) ON [PRIMARY]
END
GO

GO
IF('$(EnvironmentName)' = 'Development')
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			DECLARE @result INT;
			DECLARE @trackFileExists INT;
			DECLARE @fileName VARCHAR(100) = 'SeedData'

			EXEC @trackFileExists = dbo.TrackFileExists @fileName;

			IF(@trackFileExists = 1)
			BEGIN
				PRINT('Skipped - FileName:SeedData - $(EnvironmentName) and TrackFile Status: ' + CAST(@result AS VARCHAR));
				RETURN;
			END

			DECLARE 
				@NewRoleName VARCHAR(50) = 'Admin',
				@NewUserId INT,
				@NewPublicProductId UNIQUEIDENTIFIER,
				@NewAdminUsername VARCHAR(50) = 'Admin',
				@NewAdminRoleName VARCHAR(50) = 'Admin',
				@NewUserRoleName VARCHAR(50) = 'User';

			EXEC dbo.CreateUser
				@Username = @NewAdminUsername,
				@Email = 'admin@org.com',
				@FirstName = 'admin',
				@LastName = 'admin',
				@Password = '$2b$10$P9ATvoejRSnFgEcsqpqDFOO0FkiZpL85FZ4Jbm2/yo4mYqxZMW7RK', -- Admin123
				@UserId = @NewUserId OUTPUT;
			PRINT('Create User: ' + CAST(ISNULL(@NewUserId, 0) AS VARCHAR(100)) + ' - FileName:SeedData - $(EnvironmentName)')
			
			EXEC dbo.AssignUserToRole @NewAdminUsername, @NewRoleName;
			PRINT('Assign User to Role: Username: ' + CAST(ISNULL(@NewAdminUsername, 0) AS VARCHAR(100)) + '- RoleId: ' + ISNULL(CAST(@NewRoleName AS VARCHAR(100)), '0') + ' - FileName:SeedData - $(EnvironmentName)')
			
			EXEC dbo.ActivateUser 
				@Username = @NewAdminUsername;
			PRINT('Activate User: ' + CAST(ISNULL(@NewAdminUsername, 0) AS VARCHAR(100)) + ' - FileName:SeedData - $(EnvironmentName)')
			
			DECLARE 
				@Username VARCHAR(50),
				@Email VARCHAR(50),
				@Confirmed BIT,
				@Disabled BIT,
				@Id INT;

			EXEC dbo.AddProduct
				@Username = @NewAdminUsername,
				@ProductName = 'Test Product',
				@Description = 'Test Description',
				@Quantity = 1,
				@PublicProductId = @NewPublicProductId OUTPUT;
			PRINT('Add Product: ' + ISNULL(CAST(@NewPublicProductId AS VARCHAR(100)), '0') + ' - FileName:SeedData - $(EnvironmentName)')
			
			EXEC dbo.AddProductPrice
				@Username = @NewAdminUsername,
				@PublicProductId = @NewPublicProductId,
				@Price = 12.99,
				@CurrencyCode = 'USD'
			PRINT('Add price to product: ' + ISNULL(CAST(@NewPublicProductId AS VARCHAR(100)), '0') + ' - FileName:SeedData - $(EnvironmentName)')


			EXEC dbo.UpdateItemInInventory
				@Username = @NewAdminUsername,
				@PublicProductId = @NewPublicProductId,
				@Quantity = 12
			PRINT('Update Inventory: ' + ISNULL(CAST(@NewPublicProductId AS VARCHAR(100)), '0') + ' - FileName:SeedData - $(EnvironmentName)')
		
			EXEC dbo.TrackFile @fileName;
		
		COMMIT TRANSACTION
	END TRY 
	BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
		
		DECLARE @errMessage VARCHAR(1200) = 'Error: ' + CAST(ERROR_NUMBER() AS VARCHAR(100)) + ' at line ' + CAST(ERROR_LINE() AS VARCHAR(100)) + ' in ' + ISNULL(ERROR_PROCEDURE(), 'Ad-hoc') + ': ' + ERROR_MESSAGE();
        THROW 50001, @errMessage, 1;
	END CATCH
END
GO

GO
PRINT N'Update complete.';


GO
