apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "component-api.fullname" . }}
spec:
  parentRefs:
    - name: {{ include "gateway-api.fullName" . }}-gateway
  rules:
    - backendRefs:
        - name: your-service-name
          port: 80