apiVersion: v1
kind: Ingress
metadata:
  name: {{ include "component-api.fullName" . }}
  labels:
    app.kubernetes.io/name: {{ include "component-api.appName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "component-api.fullChartName" . }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /testpath
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "component-api.fullName" . }}
                port:
                  number: {{ .Values.service.port }}





