version: '3.8'

services:
  api:
    build:
      context: ${API_PROJECT_PATH}
      dockerfile: Dockerfile
    container_name: api-${CONTAINER_NAME}
    restart: always
    ports:
      - "3001:8080"
      - "3002:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__InventoryDb=${DB_CONNECTION}
      - ConnectionStrings__EventStoreDb=${EVENTSTORE_CONNECTION}
      - ConnectionStrings__RabbitMQ=${RABBITMQ_CONNECTION}
      - Security__AccessToken__Key=${SECURITY_ACCESS_KEY}
      - Security__AccessToken__Expiry=${SECURITY_ACCESS_EXPIRY}
      - Security__RefreshToken__Key=${SECURITY_REFRESH_KEY}
      - Security__RefreshToken__Expiry=${SECURITY_REFRESH_EXPIRY}
      - Security__ConfirmationToken__Key=${SECURITY_CONFIRM_KEY}
      - Security__ConfirmationToken__Expiry=${SECURITY_CONFIRM_EXPIRY}
      - Security__Audience=${SECURITY_AUDIENCE}
      - Security__Issuer=${SECURITY_ISSUER}
    networks:
      - app-network
      - internal-network

networks:
  app-network:
    external: true
  internal-network:
    external: true