apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "secrets.componentName" . }}-infisical-secret
  labels:
    app: infisical-integration
  annotations:
  namespace: {{ include "application.fullNamespace" . }}
spec:
  syncConfig:
    {{- toYaml .Values.secret.syncConfig | nindent 4 }}
    resyncInterval: 10s
    instantUpdates: false

  authentication:
    universalAuth:
      secretsScope:
        projectId: {{ .Values.secret.projectId }}
        envSlug: {{ .Values.secret.envSlug }}
        secretsPath: /{{ .Values.secret.name }}/{{ .Values.secret.component }}
      credentialsRef:
        secretName: {{ .Values.secret.infisicalConfig.secretName }}
        secretNamespace: {{ include "infisicalConfig.fullNamespace" . }}

  managedKubeSecretReferences:
    - secretName: {{ include "secrets.componentName" . }}-managed-secret
      secretNamespace: {{ include "application.fullNamespace" . }}
      creationPolicy: "Orphan"