application:
  namespace:
  environment:

secret:
  # Infisical Secret Sync Configurations
  infisicalConfig:
    environment:
    namespace: platform-secrets
    secretName: universal-auth-credentials-secrets
    projectId:
    envSlug:
    
  syncConfig:
    resyncInterval: 10s
    instantUpdates: false
