CREATE TABLE [dbo].[Password]
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	[Disabled] BIT NOT NULL DEFAULT 0,
	[PasswordHash] VARBINARY(60) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    DisabledAt DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT [User_Password] FOREIGN KEY (UserId) REFERENCES [dbo].[User](Id) ON DELETE CASCADE,
)

GO

CREATE UNIQUE NONCLUSTERED INDEX IX_User_Password ON [Password](UserId)
INCLUDE ([PasswordHash]);