CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(100) NOT NULL,
	Price DECIMAL(19, 4) NOT NULL,
	CurrencyCode CHAR(3) NOT NULL,
	Quantity INT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
)
