CREATE TABLE [dbo].[Role]
(
	Id INT IDENTITY PRIMARY KEY,
	PublicId UNIQUEIDENTIFIER DEFAULT NEWID(),
	[Name] VARCHAR(50) NOT NULL,
	[Default] BIT NOT NULL DEFAULT 0,
)

GO

CREATE NONCLUSTERED INDEX IX_Role_Name_Id ON [Role] ([Name])
INCLUDE ([Id]);

GO;
