CREATE TABLE [dbo].UsersRole
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Role] VARCHAR(50) NOT NULL,
	[UserId] INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT [FK_AssignUserToRole_User] FOREIGN KEY (UserId) REFERENCES [dbo].[User]([Id]),
	CONSTRAINT [PK_UsersRole] PRIMARY KEY (Id)
)