CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	Username VARCHAR(50) UNIQUE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Confirmed BIT NOT NULL DEFAULT 0,
	[Disabled] BIT NOT NULL DEFAULT 0,
	DisabledAt DATETIME NULL,
	ConfirmedAt DATETIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_User] PRIMARY KEY (Id)
)

GO

CREATE UNIQUE NONCLUSTERED INDEX IX_Username_Disabled
ON [User] (Username)
INCLUDE (Id)
WHERE Confirmed = 1 AND [Disabled] = 0;

GO