name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-dacpac:
    runs-on: ubuntu-latest
    steps:
      - name: Install SQLPackage & SQLCMD
        run: |
          wget
      - name: Check SQLPackage
        run: |
          SQLPackage
  validate-dacpac:
    runs-on: ubuntu-latest
    needs: build-dacpac
    environment: development
    steps:
      - name: Test
        run: dotnet build ./src/something/something --configuration Release

  deploy-dacpac-k8s:
    runs-on: self-hosted
    needs: validate-dacpac
    environment: dev