apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secrets"
  namespace: {{ include "application.namespace" .}}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  clientSecret: {{ .Values.clientSecret | b64enc | quote }}
  clientId: {{ .Values.clientId | b64enc | quote }}